import { App } from "vue"; 
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faArrowLeft,
    faArrowRight,
    faBackward,
    faBars,
    faBarsStaggered,
    faBolt,
    faBookOpen,
    faBookQuran,
    faBookmark,
    faBuilding,
    faCaretDown,
    faCaretLeft,
    faCaretRight,
    faCaretUp,
    faCheck,
    faCirclePause,
    faCirclePlay,
    faCity,
    faClockRotateLeft,
    faCode,
    faCopy,
    faDownload,
    faEllipsisVertical,
    faExpand,
    faEye,
    faForward,
    faGear,
    faGlobe,
    faHome,
    faInfoCircle,
    faLightbulb,
    faLink,
    faList,
    faMinimize,
    faMinus,
    faMobileScreen,
    faMoon,
    faPhone,
    faPlay,
    faPlus,
    faRepeat,
    faSearch,
    faShieldHalved,
    faSliders,
    faSpinner,
    faStar,
    faSun,
    faTimes,
    faTimesCircle,
    faTrash,
    faUser
} from "@fortawesome/free-solid-svg-icons";
import {
    faFacebookF,
    faWhatsapp,
    faTelegram
} from "@fortawesome/free-brands-svg-icons";

library.add(
    faSliders,
    faGlobe,
    faCaretUp,
    faCaretDown,
    faSearch,
    faStar,
    faTrash,
    faTimes,
    faTimesCircle,
    faSun,
    faMoon,
    faLightbulb,
    faExpand,
    faMinimize,
    faPlus,
    faMinus,
    faCopy,
    faBookmark,
    faBookQuran,
    faBookOpen,
    faGear,
    faArrowLeft,
    faArrowRight,
    faClockRotateLeft,
    faInfoCircle,
    faRepeat,
    faForward,
    faBackward,
    faCirclePlay,
    faCirclePause,
    faCirclePause,
    faEllipsisVertical,
    faSpinner,
    faDownload,
    faCaretRight,
    faCaretLeft,
    faLink,
    faUser,
    faCheck,
    faBolt,
    faCity,
    faBars,
    faPlay,
    faHome,
    faList,
    faClockRotateLeft,
    faMobileScreen,
    faBarsStaggered,
    faEye,
    faBuilding,
    faShieldHalved,
    faCode,
    faPhone,
    faFacebookF,
    faWhatsapp,
    faTelegram
);

export default {
    install(app: App) {
        app.component(FontAwesomeIcon.name, FontAwesomeIcon);
    }
}